name: packages
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.*
  - pytorch::pytorch=1.7.1
  - pytorch::torchvision=0.8.2
  - cudatoolkit=10.1
  - pandas=1.3.*
  - scanpy=1.8.*
  - seaborn=0.11.*
